// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {BonsaiTree} from "../src/BonsaiTree.sol";
import {Base64} from "openzeppelin-contracts/utils/Base64.sol";
import {IERC721Errors} from "openzeppelin-contracts/interfaces/draft-IERC6093.sol";
import {Ownable} from "openzeppelin-contracts/access/Ownable.sol";

contract BonsaiTreeTest is Test {
    BonsaiTree nft;
    address alice = makeAddr("alice");
    address bob = makeAddr("bob");
    address royaltyWallet = makeAddr("royalties");

    string constant VIEWER = "https://mydigitalbonsai.com/#dna=";
    string constant IMAGE = "https://mydigitalbonsai.com/nft-placeholder.png";
    uint96 constant ROYALTY_BPS = 500; // 5%

    // Real envelopes generated by the game's own sim (js/sim.js dnaEncode):
    // a 10-day cared-for tree (123 segments when replayed)…
    string constant LIVE_DNA =
        "1RZA7DsMgEETvMvUWy_JZzB1SU1juYuUAjtJEuXuEZTM07GNGA8MXHzQTHPv-RAsWk-CFFtyzaig6luBAU8EbrZZ0Huxo64oO0U1WPK69Q1I0vefTfOlz7pBgSyG41ekidIid19-QF5s2QodENUbHlMu0EYZSK6PPV942wlA8MzqHygaEoZTA6KKJFQhDGfOEJbACoUM8Jka7OysQxn-ajujt9wc";
    uint64 constant LIVE_T = 864000;
    // …and a tree that died of neglect around sim-day 5.
    string constant DEAD_DNA = "1q1YqU7Iy0lEqTk1NUbIy1VFKV7IyNDc3NTAwNDMAAR2lYiUrAx2lEiUrQwNjMwuQSKqSVXRsLQA";
    uint64 constant DEAD_T = 1036800;

    // treeId = keccak256("seed:genesisMs"); genesis for both fixtures is
    // Date.UTC(2026,3,1) = 1775001600000
    bytes32 constant TREE_A = keccak256("1234:1775001600000");
    bytes32 constant TREE_B = keccak256("5:1775001600000");

    function setUp() public {
        nft = new BonsaiTree(VIEWER, IMAGE, royaltyWallet, ROYALTY_BPS);
    }

    function _mintLive(address as_) internal returns (uint256) {
        vm.prank(as_);
        return nft.mint(TREE_A, LIVE_DNA, LIVE_T);
    }

    function test_MintStoresDnaAndStartsAtId1() public {
        vm.expectEmit(true, true, true, true);
        emit BonsaiTree.Minted(1, TREE_A, alice);
        uint256 id = _mintLive(alice);
        assertEq(id, 1);
        assertEq(nft.ownerOf(1), alice);
        assertEq(nft.dnaOf(1), LIVE_DNA);
        assertEq(nft.simT(1), LIVE_T);
        assertEq(nft.tokenOfTree(TREE_A), 1);
        assertEq(nft.treeOf(1), TREE_A);
        assertEq(nft.nextId(), 2);
    }

    function test_MintSameTreeTwiceReverts() public {
        _mintLive(alice);
        vm.prank(bob);
        vm.expectRevert(abi.encodeWithSelector(BonsaiTree.TreeAlreadyMinted.selector, TREE_A));
        nft.mint(TREE_A, LIVE_DNA, LIVE_T);
    }

    function test_MintZeroTreeIdReverts() public {
        vm.prank(alice);
        vm.expectRevert(BonsaiTree.InvalidTreeId.selector);
        nft.mint(bytes32(0), LIVE_DNA, LIVE_T);
    }

    function test_MintEmptyOrOversizeDnaReverts() public {
        vm.prank(alice);
        vm.expectRevert(BonsaiTree.InvalidDna.selector);
        nft.mint(TREE_A, "", LIVE_T);

        string memory huge = new string(nft.MAX_DNA_LEN() + 1);
        vm.prank(alice);
        vm.expectRevert(BonsaiTree.InvalidDna.selector);
        nft.mint(TREE_A, huge, LIVE_T);
    }

    function test_UpdateByOwnerBumpsSimT() public {
        uint256 id = _mintLive(alice);
        vm.prank(alice);
        vm.expectEmit(true, false, false, true);
        emit BonsaiTree.Updated(id, LIVE_T + 86400);
        nft.update(id, DEAD_DNA, LIVE_T + 86400);
        assertEq(nft.dnaOf(id), DEAD_DNA);
        assertEq(nft.simT(id), LIVE_T + 86400);
    }

    function test_UpdateEqualSimTAllowed() public {
        uint256 id = _mintLive(alice);
        vm.prank(alice);
        nft.update(id, LIVE_DNA, LIVE_T);
        assertEq(nft.simT(id), LIVE_T);
    }

    function test_UpdateSimTRegressionReverts() public {
        uint256 id = _mintLive(alice);
        vm.prank(alice);
        vm.expectRevert(abi.encodeWithSelector(BonsaiTree.TimeWentBackwards.selector, LIVE_T, LIVE_T - 1));
        nft.update(id, LIVE_DNA, LIVE_T - 1);
    }

    function test_UpdateByNonOwnerReverts() public {
        uint256 id = _mintLive(alice);
        vm.prank(bob);
        vm.expectRevert(abi.encodeWithSelector(BonsaiTree.NotTokenOwner.selector, id));
        nft.update(id, LIVE_DNA, LIVE_T + 1);
    }

    function test_UpdateRightsFollowTransfer() public {
        uint256 id = _mintLive(alice);
        vm.prank(alice);
        nft.transferFrom(alice, bob, id);

        vm.prank(alice);
        vm.expectRevert(abi.encodeWithSelector(BonsaiTree.NotTokenOwner.selector, id));
        nft.update(id, LIVE_DNA, LIVE_T + 1);

        vm.prank(bob);
        nft.update(id, LIVE_DNA, LIVE_T + 1);
        assertEq(nft.simT(id), LIVE_T + 1);
    }

    function test_TokenUriEmbedsViewerLinkAndAge() public {
        uint256 id = _mintLive(alice);
        string memory json = _decodeTokenUri(id);
        assertTrue(_contains(json, '"name":"Pixel Bonsai #1"'));
        assertTrue(_contains(json, string.concat('"animation_url":"', VIEWER, LIVE_DNA, '"')));
        assertTrue(_contains(json, string.concat('"image":"', IMAGE, '"')));
        assertTrue(_contains(json, '{"trait_type":"Age (days)","value":10}'));
    }

    function test_TokenUriForDeadTreeEnvelope() public {
        vm.prank(alice);
        uint256 id = nft.mint(TREE_B, DEAD_DNA, DEAD_T);
        string memory json = _decodeTokenUri(id);
        // a dead tree is just history — its envelope still renders a valid token
        assertTrue(_contains(json, string.concat('"animation_url":"', VIEWER, DEAD_DNA, '"')));
        assertTrue(_contains(json, '{"trait_type":"Age (days)","value":12}'));
    }

    function test_SetViewerBaseChangesTokenUriAndIsOwnerOnly() public {
        uint256 id = _mintLive(alice);
        nft.setViewerBase("https://example.org/#dna=");
        assertTrue(_contains(_decodeTokenUri(id), '"animation_url":"https://example.org/#dna='));

        vm.prank(alice);
        vm.expectRevert(abi.encodeWithSelector(Ownable.OwnableUnauthorizedAccount.selector, alice));
        nft.setViewerBase("https://evil.example/#dna=");
    }

    function test_QueriesForNonexistentTokenRevert() public {
        vm.expectRevert(abi.encodeWithSelector(IERC721Errors.ERC721NonexistentToken.selector, 99));
        nft.tokenURI(99);
        vm.expectRevert(abi.encodeWithSelector(IERC721Errors.ERC721NonexistentToken.selector, 99));
        nft.dnaOf(99);
    }

    // ---------- royalties (ERC-2981)

    function test_RoyaltyInfoAndInterface() public {
        uint256 id = _mintLive(alice);
        (address receiver, uint256 amount) = nft.royaltyInfo(id, 1 ether);
        assertEq(receiver, royaltyWallet);
        assertEq(amount, 0.05 ether); // 500 bps of 1 ETH
        assertTrue(nft.supportsInterface(0x2a55205a)); // ERC-2981
        assertTrue(nft.supportsInterface(0x80ac58cd)); // ERC-721
    }

    function test_SetRoyaltyIsOwnerOnly() public {
        nft.setRoyalty(bob, 250);
        (address receiver, uint256 amount) = nft.royaltyInfo(1, 10000);
        assertEq(receiver, bob);
        assertEq(amount, 250);

        vm.prank(alice);
        vm.expectRevert(abi.encodeWithSelector(Ownable.OwnableUnauthorizedAccount.selector, alice));
        nft.setRoyalty(alice, 10000);
    }

    // ---------- update lock (buyer protection on a mutable token)

    function test_LockBlocksUpdateUntilExpiry() public {
        uint256 id = _mintLive(alice);
        uint64 until = uint64(block.timestamp) + 7 days;
        vm.prank(alice);
        vm.expectEmit(true, false, false, true);
        emit BonsaiTree.UpdatesLocked(id, until);
        nft.lockUpdates(id, until);

        vm.prank(alice);
        vm.expectRevert(abi.encodeWithSelector(BonsaiTree.DnaLocked.selector, id, until));
        nft.update(id, LIVE_DNA, LIVE_T + 1);

        vm.warp(until); // lock is exclusive of its expiry instant
        vm.prank(alice);
        nft.update(id, LIVE_DNA, LIVE_T + 1);
        assertEq(nft.simT(id), LIVE_T + 1);
    }

    function test_LockIsOwnerOnlyMonotonicAndCapped() public {
        uint256 id = _mintLive(alice);

        vm.prank(bob);
        vm.expectRevert(abi.encodeWithSelector(BonsaiTree.NotTokenOwner.selector, id));
        nft.lockUpdates(id, uint64(block.timestamp) + 1 days);

        uint64 until = uint64(block.timestamp) + 7 days;
        vm.prank(alice);
        nft.lockUpdates(id, until);

        // the seller may never walk a promised lock back — only extend it
        vm.prank(alice);
        vm.expectRevert(abi.encodeWithSelector(BonsaiTree.LockMayOnlyExtend.selector, until, until - 1 days));
        nft.lockUpdates(id, until - 1 days);
        vm.prank(alice);
        nft.lockUpdates(id, until + 7 days);
        assertEq(nft.updatesLockedUntil(id), until + 7 days);

        uint64 max = uint64(block.timestamp) + nft.MAX_LOCK_AHEAD();
        vm.prank(alice);
        vm.expectRevert(abi.encodeWithSelector(BonsaiTree.LockTooFarAhead.selector, max + 1, max));
        nft.lockUpdates(id, max + 1);
    }

    function test_TransferClearsLockSoBuyerPlaysImmediately() public {
        uint256 id = _mintLive(alice);
        vm.prank(alice);
        nft.lockUpdates(id, uint64(block.timestamp) + 30 days);

        vm.prank(alice);
        vm.expectEmit(true, false, false, true);
        emit BonsaiTree.UpdatesLocked(id, 0);
        nft.transferFrom(alice, bob, id);

        assertEq(nft.updatesLockedUntil(id), 0);
        vm.prank(bob);
        nft.update(id, LIVE_DNA, LIVE_T + 1); // no waiting out the seller's lock
        assertEq(nft.simT(id), LIVE_T + 1);
    }

    // ---------- helpers

    function _decodeTokenUri(uint256 id) internal view returns (string memory) {
        string memory uri = nft.tokenURI(id);
        bytes memory b = bytes(uri);
        bytes memory prefix = bytes("data:application/json;base64,");
        bytes memory payload = new bytes(b.length - prefix.length);
        for (uint256 i = 0; i < payload.length; i++) payload[i] = b[i + prefix.length];
        return string(Base64.decode(string(payload)));
    }

    function _contains(string memory haystack, string memory needle) internal pure returns (bool) {
        bytes memory h = bytes(haystack);
        bytes memory n = bytes(needle);
        if (n.length > h.length) return false;
        for (uint256 i = 0; i <= h.length - n.length; i++) {
            bool found = true;
            for (uint256 j = 0; j < n.length; j++) {
                if (h[i + j] != n[j]) { found = false; break; }
            }
            if (found) return true;
        }
        return false;
    }
}
